controlPlaneNumber: 3
workersNumber: 2
ingressNumber: 2
gpuNumberL4: 1
gpuNumberL40: 1
gpuNumberH200: 1

clusterNetwork:
  pods:
    cidrBlocks:
    - "10.244.0.0/16"
  services:
    cidrBlocks:
    - "10.96.0.0/12"
  serviceDomain: "cluster.local"

clusterLabels: {}

ccmRegional: true

identityRef:
  name: ""
  cloudName: ""
  region: ""

bastion:
  enabled: true
  spec:
    providerID: ""
    flavor: ""
    image:
      filter:
        name: ""

managedSecurityGroups:
  allowAllInClusterTraffic: false

managedSubnets:
- cidr: 10.6.0.0/24

apiServerLoadBalancer:
  enabled: true

networkMTU: 1500

externalNetwork:
  filter:
    name: ""

controlPlane:
  sshPublicKey: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  ports: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

worker:
  sshPublicKey: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  ports: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

ingress:
  sshPublicKey: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  ports: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

gpul4:
  sshPublicKey: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  ports: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

gpul40:
  sshPublicKey: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  ports: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

gpuh200:
  sshPublicKey: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  ports: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

k0s:
  version: v1.31.5+k0s.0
  api:
    extraArgs: {}
