apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: 3
  # dirty hack
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--debug=true"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      {{- with .Values.k0s.api.extraArgs }}
      api:
        extraArgs:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      network:
        provider: calico
        calico:
          mode: ipip
      extensions:
        helm:
          repositories:
            - name: openstack
              url: https://kubernetes.github.io/cloud-provider-openstack/
          charts: 
            - name: openstack-ccm
              chartname: openstack/openstack-cloud-controller-manager
              version: 2.31.1
              order: 1
              namespace: kube-system
              values: |
                secret:
                  enabled: true
                  name: openstack-cloud-config
                  create: false
                nodeSelector:
                  node-role.kubernetes.io/control-plane: "true"
                tolerations:
                  - key: node.cloudprovider.kubernetes.io/uninitialized
                    value: "true"
                    effect: NoSchedule
                  - key: node-role.kubernetes.io/control-plane
                    effect: NoSchedule
                  - key: node-role.kubernetes.io/master
                    effect: NoSchedule
                extraEnv:
                  - name: OS_CCM_REGIONAL
                    value: {{ .Values.ccmRegional | quote }}
            - name: openstack-csi
              chartname: openstack/openstack-cinder-csi
              version: 2.31.2
              order: 2
              namespace: kube-system
              values: |
                storageClass:
                  enabled: true
                  delete:
                    isDefault: false
                    allowVolumeExpansion: true
                  retain:
                    isDefault: false
                    allowVolumeExpansion: false
                secret:
                  enabled: true
                  name: openstack-cloud-config
                  create: false
                csi:
                  plugin:
                    nodePlugin:
                      kubeletDir: /var/lib/k0s/kubelet
