name: Release Charts
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
jobs:
  release:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: aws-standalone-cp-cilium-oidc
        repository: pbasov/k0rdent-templates
        tag: 0.0.1
        path: charts/aws-standalone-cp-cilium-oidc
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: aws-standalone-cp-cilium
        repository: pbasov/k0rdent-templates
        tag: 0.0.3
        path: charts/aws-standalone-cp-cilium
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: aws-standalone-cp-nocni
        repository: pbasov/k0rdent-templates
        tag: 0.0.3
        path: charts/aws-standalone-cp-nocni
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: openstack-standalone-cp-custom
        repository: pbasov/k0rdent-templates
        tag: 0.0.1
        path: charts/openstack-standalone-cp-custom
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: openstack-standalone-cp-nocni
        repository: pbasov/k0rdent-templates
        tag: 0.0.9
        path: charts/openstack-standalone-cp-nocni
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: aws-standalone-cp-nocni-gpu
        repository: pbasov/k0rdent-templates
        tag: 0.0.2
        path: charts/aws-standalone-cp-nocni-gpu
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'