name: Release Openstack Charts
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
jobs:
  release:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Chart | Push
      uses: appany/helm-oci-chart-releaser@v0.4.2
      with:
        name: openstack-standalone-cp-nocni
        repository: deatwisedog/k0rdent-templates
        tag: 0.1.0
        path: charts/openstack-standalone-cp-nocni
        registry: ghcr.io
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
        update_dependencies: 'true'
